### ISSUE TITLE
sync examples regarding specifying block_size

### ISSUE THREAD

**Issue by teichert** [bdusell/semiring-einsum#2]
First of all, thanks very much for this great work!  (I'm surprised that I'm only now finding this since it it's been on my wish-list for years!  A year or two ago, I also ran into the block_size trade off with my own generalized semiring tensordot implementation, so I'm happy to see that in here, too.)

Related to issue #1 , the [examples on the home page](https://bdusell.github.io/semiring-einsum/#basic-usage) don't specify a `block_size` which leads to a runtime error:

```python
C = torch_semiring_einsum.log_einsum(EQUATION, A, B)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-d81285427569> in <module>
----> 1 C = torch_semiring_einsum.log_einsum(EQUATION, A, B)

TypeError: result() missing 1 required keyword-only argument: 'block_size'
```

Specifying `block_size` fixes it:
```
C = torch_semiring_einsum.log_einsum(EQUATION, A, B, block_size=1)
```

One of the following should probably be done:
1. update the examples to include the block_size
2. add a default value for the block_size (this is probably preferred since new users wouldn't need to figure out the block_size thing in order to get started using the package).

Even-better, I wonder about the feasibility of implementing a more reasonable, adaptive default.
From your explanation on #1 , It sounds like you have a reasonable heuristic in mind for `block_size` as a function of input tensor shapes and available memory ([`psutil`](https://pypi.org/project/psutil/) can get access to available memory: e.g. `psutil.virtual_memory().available`).  Maybe that function could be constructed and cached at the same time that the equation is compiled and then `block_size=torch_semiring_einsum.heuristic_block_size` could indicate that it should be used to compute the block_size?  Is it worth opening a separate issue and possibly a pull-request?

**Comment by bdusell** [comment]
Thank you for your thoughtful comments! Ah, this is what happens when you don't run your own example code.

I would definitely be open to ideas about automatically choosing `block_size` -- feel free to open a separate issue. If in doubt, a value of 5 or 10 is very reasonable. It's close to the smallest amount of memory you can use, whereas any smaller than that and the overhead of launching so many kernels will seriously slow down your code.
