### ISSUE TITLE
Doesn't work with PyTorch 2?

### ISSUE THREAD

**Issue by davidweichiang** [bdusell/semiring-einsum#43]
The `pyproject.toml` (if I understand correctly) requires PyTorch >= 1.1 and < 2.0. Is that necessary?

**Comment by bdusell** [comment]
PyTorch 2 is backward-compatible with PyTorch 1 from what I understand, so we should fix this.

**Comment by AutomaticHourglass** [comment]
I also would like to get updated on this. Can someone try this on pytorch 2.0 and run the tests?

**Comment by bdusell** [comment]
Apologies that this took so long -- I've finally fixed this issue, and it will be available in the next release on PyPI!
